version: '3.8'

services:
  app:
    image: musicmanager-app:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/musicmanager
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
    volumes:
      - maven-repo:/root/.m2

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  maven-repo:
    driver: local
